<template>
  <div class="about">
    <h1>This is an about page</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo quasi dolor possimus. Laudantium quos sequi itaque quibusdam voluptatem amet et praesentium ea, repudiandae eos, suscipit alias dolore atque labore vero delectus neque dolorem, numquam fugit? Quo quod dolorum, quibusdam eligendi iusto praesentium sapiente provident odio pariatur repellat necessitatibus, possimus facilis deserunt consequuntur velit? Doloremque officia magnam quod in asperiores aliquid cumque ut fuga! Recusandae, corrupti fugit? Aliquid neque expedita minima adipisci labore veniam eaque, vero quia perferendis quas amet sit ea rem natus itaque quasi cum! Aliquid mollitia vel saepe ab aut voluptates minus quaerat eum, cumque pariatur fugit corrupti.</p>

    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo quasi dolor possimus. Laudantium quos sequi itaque quibusdam voluptatem amet et praesentium ea, repudiandae eos, suscipit alias dolore atque labore vero delectus neque dolorem, numquam fugit? Quo quod dolorum, quibusdam eligendi iusto praesentium sapiente provident odio pariatur repellat necessitatibus, possimus facilis deserunt consequuntur velit? Doloremque officia magnam quod in asperiores aliquid cumque ut fuga! Recusandae, corrupti fugit? Aliquid neque expedita minima adipisci labore veniam eaque, vero quia perferendis quas amet sit ea rem natus itaque quasi cum! Aliquid mollitia vel saepe ab aut voluptates minus quaerat eum, cumque pariatur fugit corrupti.</p>

    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo quasi dolor possimus. Laudantium quos sequi itaque quibusdam voluptatem amet et praesentium ea, repudiandae eos, suscipit alias dolore atque labore vero delectus neque dolorem, numquam fugit? Quo quod dolorum, quibusdam eligendi iusto praesentium sapiente provident odio pariatur repellat necessitatibus, possimus facilis deserunt consequuntur velit? Doloremque officia magnam quod in asperiores aliquid cumque ut fuga! Recusandae, corrupti fugit? Aliquid neque expedita minima adipisci labore veniam eaque, vero quia perferendis quas amet sit ea rem natus itaque quasi cum! Aliquid mollitia vel saepe ab aut voluptates minus quaerat eum, cumque pariatur fugit corrupti.</p>

    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo quasi dolor possimus. Laudantium quos sequi itaque quibusdam voluptatem amet et praesentium ea, repudiandae eos, suscipit alias dolore atque labore vero delectus neque dolorem, numquam fugit? Quo quod dolorum, quibusdam eligendi iusto praesentium sapiente provident odio pariatur repellat necessitatibus, possimus facilis deserunt consequuntur velit? Doloremque officia magnam quod in asperiores aliquid cumque ut fuga! Recusandae, corrupti fugit? Aliquid neque expedita minima adipisci labore veniam eaque, vero quia perferendis quas amet sit ea rem natus itaque quasi cum! Aliquid mollitia vel saepe ab aut voluptates minus quaerat eum, cumque pariatur fugit corrupti.</p>
  </div>
</template>
